version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.49
    steps:
      - checkout
      - run:
          name: add ssh key for github pages
          command: echo $PAGES_DEPLOY_SSH_KEY | base64 -d > ~/.ssh/id_rsa_pages
      - run:
          name: add git-subtree
          command: apk add --no-cache git-subtree
      - run:
          name: debug
          command: cat /etc/ssh/ssh_config
          environement:
            GIT_SSH_COMMAND: ssh -i ~/.ssh/id_rsa_pages
      - run:
          name: Publish Site
          command: ./publish
          environment: 
            GIT_SSH_COMMAND: ssh -v -o IdentitiesOnly=yes -i ~/.ssh/id_rsa_pages

