version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:0.49
    steps:
      - checkout
      - run:
          name: add ssh key for github pages
          command: echo $PAGES_DEPLOY_SSH_KEY | base64 -d > ~/.ssh/id_rsa_pages
      - run:
          name: set ssh key permissions
          command: chmod 0600 ~/.ssh/id_rsa_pages
      - run:
          name: add git-subtree
          command: apk add --no-cache git-subtree
      - deploy:
          name: Publish Site
          command: |
                  if [ "${CIRCLE_BRANCH}" = "master" ]; then
                    sed -i "" '/public/d' ./.gitignore
                    git add .
                    git commit -m "Edit .gitignore to publish"
                    git remote add public git@github.com:pascalpdx/pascalpdx.github.io.git
                    HUGO_ENV=production hugo -v -s ./
                    git push public `git subtree split --prefix public master`:master --force
                    git reset HEAD~
                    git checkout .gitignore
                  else
                    echo "Not master branch, dry run only, not pushing changes to site"
                  fi
          environment: 
            GIT_SSH_COMMAND: ssh -o IdentitiesOnly=yes -i ~/.ssh/id_rsa_pages
