version: 2
jobs:
  build:
    docker:
      - image: jguyomard/hugo-builder:0.49
    steps:
      - checkout
      - run:
          name: add ssh key for github pages
          command: echo $PAGES_DEPLOY_SSH_KEY | base64 -d > ~/.ssh/id_rsa_pages
      - run:
          name: Publish Site
          command: GIT_SSH_COMMAND='ssh -i ~/.ssh/id_rsa_pages' ~/project/publish

